#!/bin/bash
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='mu' --seed=42 --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='alpha' --seed=42 --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='homo' --seed=42  --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='lumo' --seed=42 --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='gap' --seed=42  --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='r2' --seed=42 --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='zpve' --seed=42 --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='U0' --seed=42  --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='U' --seed=42  --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='H' --seed=42 --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='G' --seed=42  --pe='hkpe'
CUDA_VISIBLE_DEVICES=6 python spherenet_qm9.py --target='Cv' --seed=42 --pe='hkpe'