#!/bin/bash
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='zpve' --seed=42 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='U0' --seed=42 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='U' --seed=42 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='zpve' --seed=50 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='U0' --seed=50 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='U' --seed=50 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='zpve' --seed=100 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='U0' --seed=100 --pe='lappe'
CUDA_VISIBLE_DEVICES=6 python dig_schnet_qm9.py --target='U' --seed=100 --pe='lappe'