#!/bin/bash
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='lumo' --seed=42 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='gap' --seed=42 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='r2' --seed=42 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='lumo' --seed=50 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='gap' --seed=50 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='r2' --seed=50 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='lumo' --seed=100 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='gap' --seed=100 --pe='lappe'
CUDA_VISIBLE_DEVICES=5 python dig_schnet_qm9.py --target='r2' --seed=100 --pe='lappe'